version: '3'
services:
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    container_name: web
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "8000:8000"
    volumes:
      - .:/build/api
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- /build/api/api

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: